# Generated by Django 5.2.13 on 2026-04-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_service', '0001_initial'),
        ('ride_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ride_service.ride'),
        ),
    ]
