# Generated by Django 5.2.13 on 2026-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
