# Generated by Django 5.2.13 on 2026-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_service', '0004_vehiclelisting_rental_selected_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
