# Generated by Django 5.2.13 on 2026-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_service', '0005_rental_otp_ride_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='Uber Go', max_length=50),
        ),
    ]
